interface Products {
id:number
name:string
price:string
image:string
category:string
}

export const products:Products[] = [
{
    id: 0,
    name:'Accessory',
    price:'17',
    image:'/images/products/accessory1',
    category:'accessories', 
},
{
    id: 1,
    name:'Accessory',
    price:'17',
    image:'/images/products/accessory2',
    category:'accessories', 
},
{
    id: 2,
    name:'Accessory',
    price:'17',
    image:'/images/products/accessory3',
    category:'accessories', 
},
{
    id: 3,
    name:'Accessory',
    price:'17',
    image:'/images/products/accessory4',
    category:'accessories', 
},
{
    id: 4,
    name:'Accessory',
    price:'17',
    image:'/images/products/accessory5',
    category:'accessories', 
},
{
    id: 5,
    name:'Accessory',
    price:'17',
    image:'/images/products/accessory6',
    category:'accessories', 
},
{
    id: 6,
    name:'Bag',
    price:'17',
    image:'/images/products/bag1',
    category:'bags', 
},
{
    id: 7,
    name:'Bag',
    price:'17',
    image:'/images/products/bag2',
    category:'bags', 
},
{
    id: 8,
    name:'Bag',
    price:'17',
    image:'/images/products/bag3',
    category:'bags', 
},
{
    id: 9,
    name:'Bag',
    price:'17',
    image:'/images/products/bag4',
    category:'bags', 
},
{
    id: 10,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket1',
    category:'jackets', 
},
{
    id: 11,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket2',
    category:'jackets', 
},{
    id: 12,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket3',
    category:'jackets', 
},{
    id: 13,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket4',
    category:'jackets', 
},{
    id: 14,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket5',
    category:'jackets', 
},{
    id: 15,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket6',
    category:'jackets', 
},{
    id: 16,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket7',
    category:'jackets', 
},
{
    id: 17,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket8',
    category:'jackets', 
},
{
    id: 18,
    name:'Jacket',
    price:'17',
    image:'/images/products/jacket9',
    category:'jackets', 
},
{
    id: 19,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt1',
    category:'shirts', 
},
{
    id: 20,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt2',
    category:'shirts', 
},{
    id: 21,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt3',
    category:'shirts', 
},{
    id: 22,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt4',
    category:'shirts', 
},{
    id: 23,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt5',
    category:'shirts', 
},{
    id: 24,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt6',
    category:'shirts', 
},{
    id: 25,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt7',
    category:'shirts', 
},{
    id: 26,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt8',
    category:'shirts', 
},{
    id: 27,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt9',
    category:'shirts', 
},{
    id: 28,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt10',
    category:'shirts', 
},{
    id: 29,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt11',
    category:'shirts', 
},{
    id: 30,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt12',
    category:'shirts', 
},{
    id: 31,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt13',
    category:'shirts', 
},{
    id: 32,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt14',
    category:'shirts', 
},{
    id: 33,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt15',
    category:'shirts', 
},{
    id: 34,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt16',
    category:'shirts', 
},{
    id: 35,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt17',
    category:'shirts', 
},{
    id: 36,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt18',
    category:'shirts', 
},{
    id: 37,
    name:'Shirt',
    price:'17',
    image:'/images/products/shirt19',
    category:'shirts', 
},{
    id: 38,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe1',
    category:'shoes', 
},{
    id: 39,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe2',
    category:'shoes', 
},{
    id: 40,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe3',
    category:'shoes', 
},{
    id: 41,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe4',
    category:'shoes', 
},{
    id: 42,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe5',
    category:'shoes', 
},
{
    id: 43,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe6',
    category:'shoes', 
},
{
    id: 44,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe7',
    category:'shoes', 
},
{
    id: 45,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe8',
    category:'shoes', 
},
{
    id: 46,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe9',
    category:'shoes', 
},
{
    id: 47,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe10',
    category:'shoes', 
},
{
    id: 48,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe11',
    category:'shoes', 
},{
    id: 49,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe12',
    category:'shoes', 
},{
    id: 50,
    name:'Shoe',
    price:'17',
    image:'/images/products/shoe13',
    category:'shoes', 
},
{
    id: 51,
    name:'Watch',
    price:'17',
    image:'/images/products/watch1',
    category:'watches', 
},
{
    id: 52,
    name:'Watch',
    price:'17',
    image:'/images/products/watch2',
    category:'watches', 
},
{
    id: 53,
    name:'Watch',
    price:'17',
    image:'/images/products/watch3',
    category:'watches', 
},
{
    id: 54,
    name:'Watch',
    price:'17',
    image:'/images/products/watch4',
    category:'watches', 
},
{
    id: 55,
    name:'Watch',
    price:'17',
    image:'/images/products/watch5',
    category:'watches', 
},
{
    id: 56,
    name:'Watch',
    price:'17',
    image:'/images/products/watch6',
    category:'watches', 
},

]